"""Data generation for Test 4: joint r + τ estimation from Q/U polarization maps.

Extends Test 3 (τ-only estimation) to simultaneous inference of the
tensor-to-scalar ratio r and the optical depth τ. Both parameters affect
the CMB polarization power spectra: τ modifies the large-scale EE
reionization bump, while r controls the amplitude of the primordial
B-mode signal at large angular scales. Joint estimation is relevant to
the Simons Observatory's goal of constraining r ≲ 0.01 and is a
significantly harder inference problem than fixing either parameter.

Uses realistic CAMB power spectra with varying (r, τ) pairs, where
r ∈ [0, 0.01] is sampled uniformly in log(r + ε) space and τ ∈ [0.03, 0.08]
is sampled uniformly, following the same pre-computation strategy as Test 3.

FITS cache format (used by train_test4.py and run_test4_popeye.slurm):
  HDU 0 — PrimaryHDU (empty)
  HDU 1 — ImageHDU "R_VALUES"  (float32, shape n_spectra)
  HDU 2 — ImageHDU "TAU_VALUES" (float32, shape n_spectra)
  HDU 3 — ImageHDU  "CL_EE"  (float64, shape n_spectra × lmax+1)
  HDU 4 — ImageHDU  "CL_BB"  (float64, shape n_spectra × lmax+1)
"""

import numpy as np
import healpy as hp

from .data_generation_test2 import create_sky_mask

NSIDE = 16
LMAX = 3 * NSIDE - 1  # 47
TAU_MIN = 0.03
TAU_MAX = 0.08
R_MIN = 0.0
R_MAX = 0.01
N_CAMB_SPECTRA = 5000  # Paper: 5000 pre-computed spectra
R_LOG_EPSILON = 1e-4  # Offset for log(r + epsilon) sampling;
                       # chosen so log(0 + ε) ≈ -9.2, well below log(r_min)=−4.6;
                       # small enough to avoid bias at r=0

# Planck 2018 best-fit (other parameters fixed, only r and τ vary)
PLANCK_PARAMS = {
    "H0": 67.4,
    "ombh2": 0.0224,
    "omch2": 0.120,
    "As": 2.1e-9,
    "ns": 0.965,
}


def generate_camb_spectra_r_tau(
    r: float, tau: float, lmax: int = LMAX
) -> tuple[np.ndarray, np.ndarray]:
    """Generate CAMB E-mode and B-mode power spectra for given r and τ.

    Returns C_ℓ (not D_ℓ) in μK² units, compatible with hp.synfast/hp.anafast.

    Args:
        r: Tensor-to-scalar ratio.
        tau: Optical depth to reionization.
        lmax: Maximum multipole.

    Returns:
        Tuple of (cl_ee, cl_bb) arrays, each of length lmax+1.

    Raises:
        ImportError: If camb is not installed.
    """
    try:
        import camb
    except ImportError:
        raise ImportError(
            "CAMB is required for Test 4 data generation. "
            "Install with: pip install camb"
        )

    pars = camb.CAMBparams()
    pars.set_cosmology(
        H0=PLANCK_PARAMS["H0"],
        ombh2=PLANCK_PARAMS["ombh2"],
        omch2=PLANCK_PARAMS["omch2"],
        tau=tau,
    )
    pars.InitPower.set_params(
        As=PLANCK_PARAMS["As"], ns=PLANCK_PARAMS["ns"], r=r
    )
    pars.WantTensors = True
    pars.set_for_lmax(lmax)

    results = camb.get_results(pars)
    cls = results.get_total_cls(lmax, CMB_unit="muK", raw_cl=True)

    cl_ee = cls[:, 1]  # EE
    cl_bb = cls[:, 2]  # BB (from tensors, amplitude set by r)

    # Pad or truncate to lmax+1
    if len(cl_ee) < lmax + 1:
        cl_ee = np.pad(cl_ee, (0, lmax + 1 - len(cl_ee)))
        cl_bb = np.pad(cl_bb, (0, lmax + 1 - len(cl_bb)))
    else:
        cl_ee = cl_ee[: lmax + 1]
        cl_bb = cl_bb[: lmax + 1]

    return cl_ee, cl_bb


def precompute_camb_spectra_r_tau(
    n_spectra: int = N_CAMB_SPECTRA,
    lmax: int = LMAX,
    seed: int = 12345,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Pre-compute CAMB spectra for N different (r, τ) pairs.

    r is sampled uniformly in log(r + R_LOG_EPSILON) space to better
    cover the dynamical range from r ≈ 0 to r = R_MAX. τ is sampled
    uniformly in [TAU_MIN, TAU_MAX].

    This is done once at startup, then maps are generated by randomly
    choosing from the pre-computed spectra.

    Args:
        n_spectra: Number of spectra to pre-compute.
        lmax: Maximum multipole.
        seed: Random seed for (r, τ) values.

    Returns:
        Tuple of (r_values, tau_values, cl_ee_array, cl_bb_array):
        - r_values: shape (n_spectra,)
        - tau_values: shape (n_spectra,)
        - cl_ee_array: shape (n_spectra, lmax+1)
        - cl_bb_array: shape (n_spectra, lmax+1)
    """
    rng = np.random.default_rng(seed)

    # Sample r uniformly in log(r + epsilon) space
    log_r_min = np.log(R_LOG_EPSILON)
    log_r_max = np.log(R_MAX + R_LOG_EPSILON)
    r_values = np.exp(rng.uniform(log_r_min, log_r_max, size=n_spectra)) - R_LOG_EPSILON

    # Sample τ uniformly
    tau_values = rng.uniform(TAU_MIN, TAU_MAX, size=n_spectra)

    cl_ee_array = np.zeros((n_spectra, lmax + 1), dtype=np.float64)
    cl_bb_array = np.zeros((n_spectra, lmax + 1), dtype=np.float64)

    for i in range(n_spectra):
        cl_ee, cl_bb = generate_camb_spectra_r_tau(r_values[i], tau_values[i], lmax)
        cl_ee_array[i] = cl_ee
        cl_bb_array[i] = cl_bb
        if (i + 1) % 500 == 0:
            print(f"  CAMB spectra: {i + 1}/{n_spectra}")

    return (
        r_values.astype(np.float32),
        tau_values.astype(np.float32),
        cl_ee_array,
        cl_bb_array,
    )


def generate_r_tau_map(
    r: float,
    tau: float,
    nside: int = NSIDE,
    lmax: int = LMAX,
    noise_std: float = 0.0,
    f_sky: float = 1.0,
    rng: np.random.Generator = None,
    cl_ee: np.ndarray = None,
    cl_bb: np.ndarray = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Generate Q/U maps from CAMB spectra with given r and τ.

    Args:
        r: Tensor-to-scalar ratio.
        tau: Optical depth to reionization.
        nside: HEALPix Nside.
        lmax: Maximum multipole.
        noise_std: White noise standard deviation (in μK).
        f_sky: Sky fraction.
        rng: NumPy random Generator.
        cl_ee: Pre-computed EE spectrum (optional, avoids CAMB call).
        cl_bb: Pre-computed BB spectrum (optional, avoids CAMB call).

    Returns:
        Tuple of (q_map, u_map, mask), each 1D HEALPix array.
    """
    if cl_ee is None or cl_bb is None:
        cl_ee, cl_bb = generate_camb_spectra_r_tau(r, tau, lmax)

    # Build full TEB power spectrum
    cl_tt = np.full(lmax + 1, 1e-5)  # placeholder T signal (not used for Q/U estimation, but required by hp.synfast)
    cl_te = np.zeros(lmax + 1)
    cl_eb = np.zeros(lmax + 1)
    cl_tb = np.zeros(lmax + 1)

    cl_full = np.array([cl_tt, cl_ee, cl_bb, cl_te, cl_eb, cl_tb])

    # Reproducibility via numpy random state
    if rng is not None:
        rand_state = np.random.get_state()
        seed = int(rng.integers(0, 2**31))
        np.random.seed(seed)  # healpy synfast doesn't accept numpy Generator objects, so we extract a seed and use legacy np.random.seed

    maps = hp.synfast(cl_full, nside=nside, lmax=lmax)

    if rng is not None:
        np.random.set_state(rand_state)
    q_map = maps[1].astype(np.float32)
    u_map = maps[2].astype(np.float32)

    if noise_std > 0:
        if rng is not None:
            q_map += rng.normal(0, noise_std, size=q_map.shape).astype(np.float32)
            u_map += rng.normal(0, noise_std, size=u_map.shape).astype(np.float32)
        else:
            q_map += np.random.normal(0, noise_std, size=q_map.shape).astype(np.float32)
            u_map += np.random.normal(0, noise_std, size=u_map.shape).astype(np.float32)

    mask = create_sky_mask(f_sky, nside, rng)
    q_map *= mask
    u_map *= mask

    return q_map, u_map, mask
